# Autogenerated by nbdev

d = {
    "settings": {
        "branch": "main",
        "doc_baseurl": "/bedmap",
        "doc_host": "https://fr1ll.github.io",
        "git_url": "https://github.com/fr1ll/bedmap-dev",
        "lib_path": "src/bedmap",
    },
    "syms": {},
}
