# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/001_config.ipynb.

# %% auto 0
__all__ = ['Paths', 'UmapSpec', 'Cfg']

# %% ../../nbs/001_config.ipynb 1
from typing import Optional
from pathlib import Path
from importlib.metadata import version
from uuid import uuid4

from pydantic import Field, BaseModel, UUID4
from pydantic_settings import (
    BaseSettings,
    SettingsConfigDict,
    TomlConfigSettingsSource,
    CliApp,
)

import bedmap # for version

# %% ../../nbs/001_config.ipynb 2
class Paths(BaseModel):
    image_dir: None | Path = Field(None, description="Directory for input images")
    image_glob: None | str = Field(None, description="glob pattern for input images")
    thumbnail_dir: None | Path = Field(None, description="Directory for thumbnails")
    output_dir: None | Path = Field((Path()/"clipplot_output").resolve(),
            description="Directory for output files")


class UmapSpec(BaseModel):
    n_neighbors: int = Field(15, description="Number of neighbors in UMAP")
    min_dist: float = Field(0.1, description="Minimum distance in UMAP")
    

class Cfg(BaseSettings):
    thumbnail_size: int = Field(128, description="Size of images in main bedmap view")
    model_name: str = Field("timm/vit_small_patch16_dinov3.lvd1689m",
                            description="Model name on huggingface.co/models")
    umap_spec: UmapSpec = UmapSpec()
    clipplot_version: str = Field(version(bedmap.__name__), description="Version of clipplot")
    plot_id: UUID4 = Field(default_factory=lambda: str(uuid4()), description="Unique identifier for plot")
    paths: Paths = Paths()

    model_config = SettingsConfigDict(
        env_prefix = "BEDMAP_",
        cli_parse_args = True,
        use_attribute_docstrings = True,
        cli_prog_name = "bedmap",
        cli_hide_none_type = True,
        cli_ignore_unknown_args=True,
        pyproject_toml_table_header=(),
    )
