# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/021_create-umap-layout.ipynb.

# %% auto 0
__all__ = ['umap_2d']

# %% ../../nbs/021_create-umap-layout.ipynb 2
def umap_2d(embeddings: np.ndarray, n_neighbors: int = 15, min_dist: float = 0.1,
                metric: str = "cosine", random_state: int = 42) -> np.ndarray:
    """
    Create a UMAP layout from embeddings.

    Args:
        embeddings: np.ndarray, shape (n_samples, n_features)
        n_neighbors: int, default=15
        min_dist: float, default=0.1
        n_components: int, default=2
    """
    return umap.UMAP(n_neighbors=n_neighbors, min_dist=min_dist,
                     metric=metric, random_state=random_state).fit_transform(embeddings)
