# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/021_create-umap-layout.ipynb.

# %% auto 0
__all__ = ['umap_2d', 'create_umap_col']

# %% ../../nbs/021_create-umap-layout.ipynb 1
import numpy as np
import umap
import daft
from .step import step

# %% ../../nbs/021_create-umap-layout.ipynb 3
def umap_2d(embeddings: np.ndarray, n_neighbors: int = 15, min_dist: float = 0.1,
                metric: str = "cosine", random_state: int = 42) -> np.ndarray:
    """
    Create a UMAP layout from embeddings.

    Args:
        embeddings: np.ndarray, shape (n_samples, n_features)
        n_neighbors: int, default=15
        min_dist: float, default=0.1
        n_components: int, default=2
    """
    return umap.UMAP(n_neighbors=n_neighbors, min_dist=min_dist,
                     metric=metric, random_state=random_state).fit_transform(embeddings)

# %% ../../nbs/021_create-umap-layout.ipynb 5
@step(requires=["embeddings"], provides=["umap_xys"])
def create_umap_col(df: daft.DataFrame, n_neighbors: int = 15, min_dist: float = 0.1,
                metric: str = "cosine", random_state: int = 42,
                col_namespace="umap") -> daft.DataFrame:
    """
    Create a UMAP layout from embeddings.

    Args:
        embeddings: np.ndarray, shape (n_samples, n_features)
        n_neighbors: int, default=15
        min_dist: float, default=0.1
        n_components: int, default=2
    """

    ## TODO: use namespacing for XYs column
    # embeds = np.asarray(df.select("embeddings").to_pylist()["embeddings"])
    embeds = df.select("embeddings").to_arrow()["embeddings"]
    shape = len(embeds), embeds.type.list_size
    embeds = embeds.values.to_numpy().reshape(shape)
    umap_xys = umap_2d(embeds, n_neighbors=n_neighbors, min_dist=min_dist,
                       metric=metric, random_state=random_state)
    umap_xys = daft.Series.from_numpy(umap_xys)
    return df.with_column(f"{col_namespace}_xys", umap_xys)
