# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/013_create-thumbnails.ipynb.

# %% auto 0
__all__ = ['create_thumbnails_col']

# %% ../../nbs/013_create-thumbnails.ipynb 2
import numpy as np
import daft
from PIL import Image
from .step import step

# %% ../../nbs/013_create-thumbnails.ipynb 4
def _autocontrast_normed(img_arr: np.array) -> np.array:
    """autocontrast from keras - added normalization"""
    x = img_arr.astype(float)
    mean_before = x.mean()
    ## autocontrast from Keras
    x = x - np.min(x)
    x_max = np.max(x)
    if x_max != 0:  x /= x_max
    x *= 255

    ## return to average lightness of input image
    mean_shift = x.mean() - mean_before

    return np.clip(x - mean_shift, 0, 255).astype("uint8")

# %% ../../nbs/013_create-thumbnails.ipynb 5
@daft.udf(return_dtype=daft.DataType.image(mode="RGB"))
def _autocontrast_img(arrs: daft.Series) -> np.array:
    """apply autocontrast to an image column"""
    return [_autocontrast_normed(img) for img in arrs.to_pylist()]

# %% ../../nbs/013_create-thumbnails.ipynb 9
def _shape_for_max_side(input_shape: tuple[int],
                       target_max_side: int) -> tuple[int]:
    """
    for a given input shape and a desired max side length,
    return a shape with approximately same aspect ratio satisfying max_side
    """
    w, h = input_shape
    if w >= h:
        new_w = target_max_side
        new_h = int(target_max_side * h / w)
    else:
        new_h = target_max_side
        new_w = int(target_max_side * w / h)
    return (new_w, new_h)

# %% ../../nbs/013_create-thumbnails.ipynb 10
def _shape_for_max_height(input_shape, target_height: int = 128):
    """
    Given an input shape (width, height) and a target height,
    return the new shape (width, height) with the height set to target_height,
    and the width scaled to preserve aspect ratio. The minimum width is 1.
    """
    w, h = input_shape
    scaled_width = max([int(w / h * target_height),1])
    return (scaled_width, target_height)

# %% ../../nbs/013_create-thumbnails.ipynb 11
@daft.udf(return_dtype= daft.DataType.image(mode="RGB"))
def _resize_to_max_height(arrs: daft.Series, height: int = 128) -> np.array:
    """resize each image to max height"""
    arrs = arrs.to_pylist()
    input_shapes = [a.shape[:2][::-1] for a in arrs]
    thumb_shapes = [_shape_for_max_height(s, height) for s in input_shapes]
    return [np.array(Image.fromarray(a).resize(s)) for (a, s) in zip(arrs, thumb_shapes)]

# %% ../../nbs/013_create-thumbnails.ipynb 13
@step(requires=["img"], provides=["thumb"])
def create_thumbnails_col(df: daft.DataFrame, height=128) -> daft.DataFrame:
    """create thumbnail column"""
    image_col="img"
    df = df.with_column("img_ac", _autocontrast_img(df[image_col]))
    df = df.with_column("thumb", _resize_to_max_height(df["img_ac"], height))
    return df.exclude("img_ac")
