# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/014_embed-images.ipynb.

# %% auto 0
__all__ = ['BATCH_SIZE', 'images_from_paths', 'embed_images', 'create_embeddings_col']

# %% ../../nbs/014_embed-images.ipynb 2
from pathlib import Path
from PIL import Image
import numpy as np
import torch
from tqdm import tqdm
from loguru import logger
from transformers import pipeline
import daft

from .config import Cfg
from .step import step

# %% ../../nbs/014_embed-images.ipynb 3
BATCH_SIZE = 4

# %% ../../nbs/014_embed-images.ipynb 4
def images_from_paths(pathlist):
    return (Image.open(p.as_posix()).convert("RGB").copy() for p in pathlist)

# %% ../../nbs/014_embed-images.ipynb 5
def embed_images(imagepaths : list[Path],
                 model_name : str = "timm/vit_small_patch14_reg4_dinov2.lvd142m",
                 batch_size : int = 4
                 ) -> list[np.array]:
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    pipe = pipeline(task="image-feature-extraction",
                    model=model_name, device=device, pool=True, use_fast=True)

    # logger.info("Starting embedding pipeline.")
    embeddings = []

    for out in tqdm(pipe(images_from_paths(imagepaths), batch_size=batch_size),
                    total=len(imagepaths)//batch_size):
        embeddings += out

    # logger.info("Done with embedding pipeline.")

    return np.array(embeddings)

# %% ../../nbs/014_embed-images.ipynb 7
@step(requires=["img_path"], provides=["embeddings"])
def create_embeddings_col(df: daft.DataFrame, model_name: str, batch_size: int) -> daft.DataFrame:
    """
    Embed images for a given dataframe.
    """
    ## daft encodes paths as URIs, always starting with file://
    df = df.with_column("img_path_nouri", df["img_path"].str.replace(
        pattern="^file://", replacement="", regex=True))
    paths = [Path(r["img_path_nouri"]) for r in df.select("img_path_nouri").to_pylist()]
    embeds = embed_images(paths, model_name=model_name, batch_size=batch_size)
    # fixed_size_list lets us use normal arrow methods to calculate length later
    embeds_type = daft.DataType.fixed_size_list(daft.DataType.float32(), embeds.shape[-1])
    embeds_series = daft.Series.from_numpy(embeds).cast(embeds_type)

    df_embs = daft.from_pydict({"embeddings": embeds_series,
    "img_path_nouri":  df.select("img_path_nouri").to_arrow()["img_path_nouri"]}
    )

    df = df.join(df_embs, on="img_path_nouri")

    return df.exclude("img_path_nouri")
