# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/051_main.ipynb.

# %% auto 0
__all__ = ['process_images_to_umap', 'run_recipe']

# %% ../../nbs/051_main.ipynb 1
from functools import partial

from .prepare_images import df_images_from_pattern
from .validate_images import validate_images
from .create_thumbnails import create_thumbnails_col
from .embed_images import create_embeddings_col
from .create_umap_layout import create_umap_col

# %% ../../nbs/051_main.ipynb 3
def process_images_to_umap(cfg):
    steps = [validate_images,
        partial(create_thumbnails_col, thumb_size=cfg.thumb_opts.size),
    ]
    if cfg.embed_opts is not None:
        steps.append(partial(create_embeddings_col, embed_model=cfg.embed_opts.model))
    if isinstance(cfg.umap_specs, list):
        for spec in cfg.umap_specs:
            steps.append(partial(create_umap_col, umap_specs=spec))
    elif cfg.umap_specs:
        steps.append(partial(create_umap_col, umap_specs=cfg.umap_specs))

    return steps

# %% ../../nbs/051_main.ipynb 4
def run_recipe(cfg):
    df = df_images_from_pattern(cfg.pattern)
    for fn in process_images_to_umap(cfg):
        df = fn(df)
    return df
