# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/032_manifests.ipynb.

# %% auto 0
__all__ = ['create_base_manifest', 'write_manifest']

# %% ../../nbs/032_manifests.ipynb 3
from .config import Cfg
from .step import step

from pydantic_settings import BaseSettings
from datetime import datetime
import json

# %% ../../nbs/032_manifests.ipynb 4
def create_base_manifest(cfg: BaseSettings) -> dict:
    """create the initial web manifest, add later"""

    manifest = {"creation_date": datetime.today().strftime("%d-%B-%Y-%H:%M:%S"),
                "layouts": ["umap"],
                "initial_layout": "umap",
                # "point_sizes": ,
                # "imagelist": ,
                "atlas_dir": (cfg.paths.output_dir/"atlases").as_posix(),
                "metadata": False,
                # "default_hotspots": ,
                # "custom_hotsponts": ,
                "gzipped": False,
                "config": {
                    "sizes": {
                        "atlas": 2048,
                        "cell": cfg.thumbnail_size, #FIXME
                        "lod": cfg.thumbnail_size,
                    }
                }
            }
    manifest.update(json.loads(cfg.model_dump_json()))

    return manifest


# %% ../../nbs/032_manifests.ipynb 5
def write_manifest(cfg: BaseSettings):
    """write manifest to disk"""
    manifest = create_base_manifest(cfg)
    manifest_path = cfg.paths.output_dir/"manifest.json"
    with manifest_path.open("w", encoding="utf-8") as mpath:
        json.dump(manifest, mpath, ensure_ascii=False, indent=2)

    return
