# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/002_pipeline.ipynb.

# %% auto 0
__all__ = ['step']

# %% ../../nbs/002_pipeline.ipynb 3
from functools import wraps, partial
from typing import Iterable

# from bedmap.validate_images import validate_images_from_df
# from bedmap.create_thumbnails import make_thumbnails_col
# from bedmap.embed_images import make_embeds_col
# from bedmap.create_umap_layout import make_umap_col

# %% ../../nbs/002_pipeline.ipynb 4
def step(requires: Iterable[str] = (), provides: Iterable[str] = ()):
    reqs = set(requires); provs = set(provides)
    def deco(fn):
        fn.requires = reqs
        fn.provides = provs
        @wraps(fn)
        def wrapper(df, *args, **kwargs):
            missing = fn.requires - set(df.column_names)
            if missing:
                raise ValueError(f"{fn.__name__} missing columns: {missing}")
            out = fn(df, *args, **kwargs)
            return out
        return wrapper
    return deco

# %% ../../nbs/002_pipeline.ipynb 6
# def all_steps(cfg):
#     steps = [
#         partial(validate, strict=cfg.validate_opts.strict, min_side=cfg.validate_opts.min_side),
#         partial(make_thumbnails, thumb_size=cfg.thumb_opts.size),
#     ]
#     if cfg.embed_opts is not None:
#         steps.append(partial(make_embeddings, embed_model=cfg.embed_opts.model))
#     if isinstance(cfg.umap_specs, list):
#         for spec in cfg.umap_specs:
#             steps.append(partial(make_umap, umap_specs=spec))
#     elif cfg.umap_specs:
#         steps.append(partial(make_umap, umap_specs=cfg.umap_specs))

#     return steps

# %% ../../nbs/002_pipeline.ipynb 7
# def run_recipe(cfg):
#     df = create_df_from_images(cfg.pattern)
#     for fn in all_steps(cfg):
#         df = fn(df)
#     return df
