# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/031_scaffold_output.ipynb.

# %% auto 0
__all__ = ['replace_web_strings', 'customize_web_assets', 'copy_web_assets']

# %% ../../nbs/031_scaffold_output.ipynb 3
from pathlib import Path
from shutil import copytree
from .config import Cfg
import bedmap # to access __path__

# %% ../../nbs/031_scaffold_output.ipynb 4
def replace_web_strings(web_dir: Path, from_to: dict):
    """sequentially replace strings based on dict"""
    for name in ["index.html", "assets/js/tsne.js"]:
        f = web_dir / name
        text = f.read_text()
        for k, v in from_to.items():
            text = text.replace(k, v)
        f.write_text(text)

# %% ../../nbs/031_scaffold_output.ipynb 5
def customize_web_assets(out_dir: str, tagline: str, version_number: str) -> None:
    """Customize the web assets with the given tagline and version number."""
    web_dir = out_dir / "web"
    replace_web_strings(web_dir, {
        "VERSION_NUMBER": version_number,
        "Image Fields in a Local Collection": tagline}
        )

# %% ../../nbs/031_scaffold_output.ipynb 6
def copy_web_assets(out_dir: Path) -> None:
    """
    Copy the /web directory from the bedmap source to out_dir.
    """
    src = Path(bedmap.__path__[0]) / "web"
    copytree(src, out_dir, dirs_exist_ok=True)
