# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/002_step.ipynb.

# %% auto 0
__all__ = ['step']

# %% ../../nbs/002_step.ipynb 3
from functools import wraps, partial
from typing import Iterable

# %% ../../nbs/002_step.ipynb 4
def step(requires: Iterable[str] = (), provides: Iterable[str] = ()):
    reqs = set(requires); provs = set(provides)
    def deco(fn):
        fn.requires = reqs
        fn.provides = provs
        @wraps(fn)
        def wrapper(df, *args, **kwargs):
            missing = fn.requires - set(df.column_names)
            if missing:
                raise ValueError(f"{fn.__name__} missing columns: {missing}")
            out = fn(df, *args, **kwargs)
            return out
        return wrapper
    return deco
