# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/101_test-end-to-end.ipynb.

# %% auto 0
__all__ = ['NUM_TEST_IMAGES', 'TEST_DATASET', 'images_from_paths']

# %% ../../nbs/101_test-end-to-end.ipynb 1
from tempfile import TemporaryDirectory
from pathlib import Path
import shutil
from tqdm.auto import tqdm
from PIL import Image
from loguru import logger
import sys

from .prepare_images import dl_hf_images


# %% ../../nbs/101_test-end-to-end.ipynb 2
NUM_TEST_IMAGES = 256
TEST_DATASET = "kvriza8/microscopy_images"

# easy timestamps
logger.remove()
logger.add(sys.stdout, level="INFO")

# %% ../../nbs/101_test-end-to-end.ipynb 3
def images_from_paths(pathlist):
    return (Image.open(p.as_posix()).convert("RGB").copy() for p in pathlist)

# %% ../../nbs/101_test-end-to-end.ipynb 4
with TemporaryDirectory() as tmp:
    logger.info("Downloading test images.")
    dl_hf_images(dir=Path(tmp), max_images=NUM_TEST_IMAGES)
    imagepaths = list(Path(tmp).glob("*.png"))
    gen = images_from_paths(imagepaths)
    for i in range(1):
        im = next(gen)
        im.show()
